FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the app.js and other necessary files from the api-gateway folder into the container
COPY ./api-gateway/app.js /app/app.js
COPY ./utils /utils

# Copy the rest of the app (this assumes app.js and other necessary files are in the same folder as Dockerfile)
COPY . .

# Expose the necessary port (make sure it matches your app's running port)
EXPOSE 8080

# Command to run the app
CMD ["node", "app.js"]
